#!/bin/bash
#ddev-generated

## Description: Manage parts of solr
## Usage: solr COMMAND OPTIONS
##        where COMMAND is one of: start, stop, restart, status, healthcheck, create, create_core, create_collection, delete, version, zk, auth, assert, config, export, api, package, post, postlogs
## Example: ddev solr --help

solr $@
